config/routes.rb
Rails.application.routes.draw do
  get 'new' => 'benefits_applications#new', as: :new_benefit_app
  post 'create' => 'benefits_applications#create', as: :benefit_apps
  delete 'delete_benefit_app/:benefit_app_id' => 'benefits_applications#delete_benefit_app', as: :delete_benefit_app
  get 'new_member' => 'benefits_applications#new_member', as: :new_member
  post 'create_member' => 'benefits_applications#create_member', as: :members
  post 'validate_application' => 'benefits_applications#validate_application'

  get 'sign_application' => 'benefits_applications#sign_benefits_app', as: :sign_benefits_app
  post 'save_signature' => 'benefits_applications#save_signature', as: :save_signature

  patch 'update_member/:id', to: 'benefits_applications#update_member', as: :member
  get 'members/:id', to: 'benefits_applications#edit_member', as: 'edit_member'
  get 'benefits_apps/:benefit_app_id', to: 'benefits_applications#edit_benefits_app', as: :edit_benefits_app
  get 'delete_member/:member_id' => 'benefits_applications#delete_member', as: :delete_member
  patch 'update_benefits_apps/:benefit_app_id', to: 'benefits_applications#update_benefits_app', as: :update_benefits_app
  patch 'update_benefits_apps/:benefit_app_id', to: 'benefits_applications#update_benefits_app', as: :benefit_app

  get 'job_status', to: 'benefits_applications#job_status_questions', as: :job_status_questions
  post 'save_job_status', to: 'benefits_applications#save_job_status', as: :save_job_status
  post 'update_income_info', to: 'benefits_applications#update_income_info', as: :update_income_info
  root "benefits_applications#index"
end

app/controllers/benefits_applications_controller.rb
class BenefitsApplicationsController < ApplicationController
  def index
    @apps = BenefitApp.all
  end

  def new
    @benefit_app_form = BenefitApp.new
  end

  def create
    @benefit_app_form = BenefitApp.new(benefits_permitted_params)
    if @benefit_app_form.save
      session[:benefit_app_id] = @benefit_app_form.id
      redirect_to job_status_questions_path
      # redirect_to new_member_path
    else
      render :new
    end
  end

  def job_status_questions
    @benefit_app_form = current_benefit_app
    render :ask_job_status
  end

  def save_job_status
    @benefit_app_form = current_benefit_app
    if @benefit_app_form.update(benefits_permitted_params)
      if @benefit_app_form.has_job
        render :ask_income
      else
        redirect_to new_member_path
      end
    end
  end

  def update_income_info
    @benefit_app_form = current_benefit_app
    pay_schedule = job_income_permitted_params["pay_schedule"]
    income = job_income_permitted_params["income"].to_i
    monthly_income = (pay_schedule == "monthly" ? income :  income * 2)
    if @benefit_app_form.update({monthly_income: monthly_income})
      redirect_to new_member_path
    else
      render :ask_income
    end


  end

  def delete_benefit_app
    @benefit_app = BenefitApp.find(params[:benefit_app_id])
    @benefit_app.destroy
    flash[:notice] = "The benefit app was successfully destroyed."
    redirect_to root_path
  end

  def edit_benefits_app
    @benefit_app_form = BenefitApp.find(params[:benefit_app_id])
    render :edit_benefits_app
  end

  def update_benefits_app
    @benefit_app_form = BenefitApp.find(params[:benefit_app_id])
    @members = current_members(@benefit_app_form)

    if @benefit_app_form.update(benefits_permitted_params)
      flash[:success] = "Benefits app successfully updated!"
      redirect_to new_member_path, benefit_app_id: params[:benefit_app_id]
    else
      flash.now[:error] = "Failed to update benefits app"
      render :edit_benefits_app
    end
  end

  def new_member
    benefit_app = current_benefit_app
    @is_primary = benefit_app.primary_member.present?
    @members = current_members(benefit_app)
    if @is_primary
      @member_form = benefit_app&.secondary_members.build
      render :new_secondary_member
    else
      @member_form = benefit_app&.build_primary_member
      render :new_member
    end
  end

  def edit_member
    @member_form = Member.find(params[:id])
    render :edit_member
  end

  def update_member
    @member = Member.find(params[:id])
    if @member.update(member_permitted_params)
      flash[:success] = "Member successfully updated!"
      redirect_to new_member_path
    else
      flash.now[:error] = "Failed to update member"
      render :edit_member
    end
  end

  def create_member
    benefit_app = current_benefit_app
    @members = current_members(benefit_app)
    @member_form = build_member(benefit_app)
    save_member(benefit_app, @member_form)
  end

  def sign_benefits_app
    @benefit_app_form = current_benefit_app
    render :sign_benefits_app
  end

  def save_signature
    @benefit_app_form = current_benefit_app
    if @benefit_app_form.update(benefits_permitted_params.merge({submitted_at: Date.today}))
      redirect_to root_path
    end
  end

  def validate_application
    benefit_app = current_benefit_app

    if benefit_app&.primary_member.present?
      if benefit_app.signature?
        redirect_to root_path
      else
        redirect_to sign_benefits_app_path
      end
    else
      @members = current_members(benefit_app)
      @member_form = benefit_app.build_primary_member
      render :new_member
    end
  end

  def delete_member
    benefit_app = current_benefit_app
    member_id = params[:member_id].to_s.to_i
    @members = current_members(benefit_app)
    @member_form = benefit_app.secondary_members.build

    # If we don't recognize this member as a member ID, ignore.
    unless member_id.present? and member_id.in?(benefit_app.secondary_member_ids)
      flash.now[:error] = "The member was not found."
      return redirect_to members_path
    end

    # If the member isn't in the database, ignore.
    member = Member.find_by(id: member_id)
    if member.nil?
      flash.now[:error] = "The member was not found."
      return redirect_to members_path
    end

    member.destroy

    if member.destroyed?
      flash.now[:success] = "The member #{member.full_name} was removed."
      redirect_to new_member_path
    else
      flash[:error] = "Something went wrong when attempting to remove #{member.full_name}. Please try again."
      render :new_secondary_member
    end
  end

  private

  def build_member(benefit_app)
    had_primary_member = benefit_app&.primary_member.present?

    if had_primary_member
      benefit_app.secondary_members.build(member_permitted_params)
    else
      benefit_app.build_primary_member(member_permitted_params)
    end
  end

  def save_member(benefit_app, member_form)
    had_primary_member = benefit_app&.primary_member.present?

    if member_form.save && benefit_app.save
      redirect_to new_member_path
    else
      render :new_secondary_member if had_primary_member
      render :new_member unless had_primary_member
    end
  end

  def member_permitted_params
    params.require(:member).permit(:first_name, :last_name, :date_of_birth, :is_primary)
  end

  def job_income_permitted_params
    params.require(:benefit_app).permit(:pay_schedule, :income)
  end

  def benefits_permitted_params
    params.require(:benefit_app).permit(:email_address, :address, :phone_number, :signature, :signed_date, :has_job, :monthly_income)
  end

  def current_benefit_app
    benefit_app_id = session[:benefit_app_id]
    BenefitApp.find(benefit_app_id) unless benefit_app_id.nil?
  end

  def current_members(benefit_app)
    benefit_app.reload
    members = benefit_app.secondary_members.to_a
    members = [benefit_app.primary_member] + members if benefit_app.primary_member.present?
    members
  end
end

app/helpers/benefits_applications_helper.rb
module BenefitsApplicationsHelper
end

app/views/benefits_applications/_member_list.html.erb
<table class="data-table">
  <tbody>
  <% @members.each do |member| %>
    <tr>
      <td><%= member.full_name %></td>
      <td>
        <%= link_to "Edit", edit_member_path(member) %>
        <% unless member.is_primary %>&nbsp;<%= link_to "Delete", delete_member_path(member) %><% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/benefits_applications/ask_income.html.erb
<%= form_with model: @benefit_app_form, local: true, method: :post, url: update_income_info_path, builder: FoundationalProjectFormBuilder, class: "form-card" do |f| %>
  <h2>Tell us about your monthly income.</h2>
  <%= f.vita_min_select(:pay_schedule, "What is your pay frequency?", [
    ["Monthly",  "monthly"],
    ["Biweekly",  "biweekly"]]) %>
  <%= f.vita_min_text_field(:income, "How much do you make?", options: {type: :number}) %>
  <%= f.button('Continue →', type: :submit, class: "button button--wide button--primary spacing-above-60") %>
<%end %>

app/views/benefits_applications/ask_job_status.html.erb
<%= form_with model: @benefit_app_form, local: true, method: :post, url: save_job_status_path, builder: FoundationalProjectFormBuilder, class: "form-card" do |f| %>
  <%= f.cfa_radio_set(
        :has_job,
        label_text: "<h2 class=\"form-question\">Do you have a job?</h2>".html_safe,
        collection: [
          { value: 0, label: "No, I don't have a job." },
          { value: 1, label: "Yes, I have a job." },
        ]
      )
  %>
  <%= f.button('Continue →', type: :submit, class: "button button--wide button--primary spacing-above-60") %>
<%end %>

app/views/benefits_applications/edit_benefits_app.html.erb
<%= render "shared/benefit_app_form", form_title: "Edit Benefits Application" %>

app/views/benefits_applications/edit_member.html.erb
<%= render "shared/member_form", form_title: "Edit Member", button_title: "Edit Member →" %>

app/views/benefits_applications/index.html.erb
<div class="card">
  <div class="emoji emoji-size-155 emoji--clipboard"></div>
  <h1>Submitted Applications</h1>
    <table class="data-table">
      <thead>
      <tr>
        <th>App number</th>
        <th>Date submitted</th>
        <th>Applicant</th>
        <th> </th>
        <th> </th>
      </tr>
      </thead>
      <tbody>
      <% @apps.each do |benefit_app| %>
        <tr>
          <td><%= benefit_app.id %></td>
          <td><%= benefit_app.submitted_at or 'Not Submitted' %></td>
          <td><%= benefit_app.primary_member_name %></td>
          <td><%= link_to "Delete", delete_benefit_app_path(benefit_app), method: :delete  %></td>
          <td><%= link_to "Edit", edit_benefits_app_path(benefit_app) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <%= link_to 'New Application', new_benefit_app_path , class: 'button button--primary' %>
</div>

app/views/benefits_applications/inform_of_eligibility.html.erb
<div class="card">
  <div class="emoji emoji-size-155 emoji--thumbs-up"></div>
  <h2>Great! We looked at your income and it looks like you qualify for benefits.</h2>
  <%= link_to 'Continue →', new_member_path , class: 'button button--primary' %>
</div>

app/views/benefits_applications/inform_of_ineligibilty.html.erb
<div class="card">
  <h2 class="text--red">Based on your info, you may be over the pre-tax income limit.</h2>
  <p>Your pre-tax income:</p>
  <p class="text--centered text--red">
    <strong><%= number_to_currency(@benefit_app.monthly_income * 12, unit: "$") %></strong>
  </p>
  <p>You can still apply but might not qualify.</p>
  <%= link_to 'Apply anyway', new_member_path , class: 'button' %>
</div>

app/views/benefits_applications/new.html.erb
<%= render "shared/benefit_app_form", form_title: "How can we contact you?", button_title: "Add Member →" %>

app/views/benefits_applications/new_member.erb
<%= render "shared/member_form", form_title: "Tell us about #{@member_form&.is_primary ? "yourself" : "your secondary member" }", button_title: "Add Member →" %>
<%= render 'benefits_applications/member_list', locals: {members: @members} %>
<br />
<%= button_to "Continue →", validate_application_path, class: "button button--wide button--primary", style: "margin-left: 0.125rem", disabled: !@is_primary %>

app/views/benefits_applications/sign_benefits_app.html.erb
<%= form_with model: @benefit_app_form, local: true, method: :post, url: save_signature_path, builder: FoundationalProjectFormBuilder, class: "form-card" do |f| %>
  <div class="emoji emoji-size-155 emoji--fountain-pen"></div>
  <h2>Type your full legal name here to sign the application</h2>
  <p>By entering your name you agree that you want to apply for benefits, that you have been honest on this application, and that you have read and agreed to the terms.</p>
  <%= f.vita_min_text_field(:signature, "", classes: ["form-width--long"]) %>
  <%= f.button('Sign and submit application', type: :submit, class: "button button--wide button--primary spacing-above-60") %>
<% end %>